# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PokéToday
email: cassidy@poke.today
description: > # this means to ignore newlines until "baseurl:"
  A collection of Pokémon Go resources in one nice spot. :) Tips, tricks, and
  guides for all you Pokémasters.
baseurl: "/poke" # the subpath of your site, e.g. /blog
url: "http://poke.today" # the base hostname & protocol for your site
twitter_username: cassidyjames
github_username:  cassidyjames

# Build settings
markdown: kramdown
